name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Deploy to GH Pages
      run: |
        git config --global user.email "zchang0302@gmail.com>"
        git config --global user.name "Zhipeng-Chang>"
        git remote set-url origin https://4dcd3ce5cb71a54ad9ac5d4dfe7ca3fbcd4171cd>@github.com/Zhipeng-Chang/Jackson-website>.git
        npm run deploy